import { app, BrowserWindow, Notification } from 'electron';
import { createTrayIcon } from "./tray";
import { openMatchWindow } from "./windows";

// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MATCH_WINDOW_WEBPACK_ENTRY: string;
declare const SETTINGS_WINDOW_WEBPACKENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  // eslint-disable-line global-require
  app.quit();
}

/* const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    icon: applicationIcon,
    height: 600,
    width: 800,
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MATCH_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
}; */

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  createTrayIcon();
  openMatchWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
/*app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
}); */

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    openMatchWindow();
  }
});
