/**
 *
 * @param name Should be the name we ge from server, for example
 * @param version
 */
const getMapIconPath = (name: string, version: "x64" | "x300" = "x300"): string => {
  return `/resources/map-images/${name}_${version}.webp`;
};

interface MapInfo {
  type: ("1v1" | "2v2" | "3v3" | "4v4")[];
  displayName: string;
  autoMatch: boolean;
  maxPlayers: number;
}

const mapNames: Record<string, MapInfo> = {
  // 4v4 Maps
  "8p_redball_express": {
    type: ["4v4"],
    displayName: "Red Ball Express",
    autoMatch: true,
    maxPlayers: 8,
  },
  "8p_west_wall": {
    type: ["4v4"],
    displayName: "The West Wall",
    autoMatch: true,
    maxPlayers: 8,
  },
  "8p_general_mud": {
    type: ["4v4"],
    displayName: "General Mud",
    autoMatch: true,
    maxPlayers: 8,
  },
  "8p_lorch_assault": {
    type: ["4v4"],
    displayName: "Lorch Assault",
    autoMatch: true,
    maxPlayers: 8,
  },
  "8p_la_gleize": {
    type: ["4v4"],
    displayName: "La Gleize Breakout",
    autoMatch: true,
    maxPlayers: 8,
  },
  "8p_coh2_city_17_spring_frontline": {
    type: ["4v4"],
    displayName: "City 17",
    autoMatch: true,
    maxPlayers: 8,
  },
  "8p_coh2_thesteppes_frontline": {
    type: ["4v4"],
    displayName: "Steppes",
    autoMatch: true,
    maxPlayers: 8,
  },
  "8p_hill_400": {
    type: ["4v4"],
    displayName: "Hill 400",
    autoMatch: true,
    maxPlayers: 8,
  },
  "8p_lazenrath_ambush": {
    type: ["4v4"],
    displayName: "Lanzerath Ambush",
    autoMatch: true,
    maxPlayers: 8,
  },
  "8p_nordwind": {
    type: ["4v4"],
    displayName: "Nordwind",
    autoMatch: true,
    maxPlayers: 8,
  },
  "8p_essen_steelworks": {
    type: ["4v4"],
    displayName: "Essen Steelworks",
    autoMatch: true,
    maxPlayers: 8,
  },
  "8p_lienne_forest": {
    type: ["4v4"],
    displayName: "Lienne Forest",
    autoMatch: true,
    maxPlayers: 8,
  },
  roadtoarnhem: {
    type: ["4v4"],
    displayName: "Road to Arnhem",
    autoMatch: true,
    maxPlayers: 8,
  },
  "8p_port_of_hamburg": {
    type: ["4v4"],
    displayName: "Port of Hamburg",
    autoMatch: true,
    maxPlayers: 8,
  },
  "8p_whiteball_express": {
    type: ["4v4", "3v3"],
    displayName: "Whiteball Express",
    autoMatch: true,
    maxPlayers: 8,
  },
  "6_8_brody": {
    type: ["4v4"],
    displayName: "Brody",
    autoMatch: false,
    maxPlayers: 8,
  },
  "8p_city_17_spring_frontline_primary": {
    type: ["4v4"],
    displayName: "City 17",
    autoMatch: false,
    maxPlayers: 8,
  },
  "8p_city_17_winter_battlefield_primary": {
    type: ["4v4"],
    displayName: "City 17 Winter",
    autoMatch: false,
    maxPlayers: 8,
  },
  "6p_mud_valley": {
    type: ["4v4"],
    displayName: "Donbas Valley",
    autoMatch: false,
    maxPlayers: 8,
  },
  "4_6_rostov": {
    type: ["4v4"],
    displayName: "Faceoff at Rostov",
    autoMatch: false,
    maxPlayers: 8,
  },
  "6p_hill_331": {
    type: ["4v4"],
    displayName: "Hill 331",
    autoMatch: false,
    maxPlayers: 8,
  },
  "8p_stalingrad": {
    type: ["4v4"],
    displayName: "Lazur Factory",
    autoMatch: false,
    maxPlayers: 8,
  },
  "8p_montargis_region": {
    type: ["4v4"],
    displayName: "Montargis Region",
    autoMatch: false,
    maxPlayers: 8,
  },
  "8p_narva_v2": {
    type: ["4v4"],
    displayName: "Narva River",
    autoMatch: false,
    maxPlayers: 8,
  },
  "6p_swamps": {
    type: ["4v4"],
    displayName: "Pinsk Marshes",
    autoMatch: false,
    maxPlayers: 8,
  },
  "8p_sittard_2": {
    type: ["4v4"],
    displayName: "Sittard Summer",
    autoMatch: false,
    maxPlayers: 8,
  },
  "8p_thesteppes_frontline_primary": {
    type: ["4v4"],
    displayName: "Steppes",
    autoMatch: false,
    maxPlayers: 8,
  },
  "8p_angermuende": {
    type: ["4v4"],
    displayName: "Angermünde",
    autoMatch: false,
    maxPlayers: 8,
  },
  "8p_anklet": {
    type: ["4v4"],
    displayName: "Anklet & Archery",
    autoMatch: false,
    maxPlayers: 8,
  },
  "8p_roadtoarnhem": {
    type: ["4v4"],
    displayName: "Road to Arnhem",
    autoMatch: false,
    maxPlayers: 8,
  },
  // 3v3 Maps
  "6p_across_the_rhine": {
    type: ["3v3"],
    displayName: "Across the Rhine",
    autoMatch: true,
    maxPlayers: 6,
  },
  "6p_fields_of_winnekendonk": {
    type: ["3v3"],
    displayName: "Fields of Winnekendonk",
    autoMatch: true,
    maxPlayers: 6,
  },
  "6p_port_of_hamburg": {
    type: ["3v3"],
    displayName: "Port of Hamburg",
    autoMatch: true,
    maxPlayers: 6,
  },
  "6p_rzhev_frontline": {
    type: ["3v3"],
    displayName: "Rzhev Frontline",
    autoMatch: true,
    maxPlayers: 6,
  },
  "4p_coh2_okariver_frontline": {
    type: ["3v3"],
    displayName: "Oka River",
    autoMatch: true,
    maxPlayers: 6,
  },
  "6p_angermuende": {
    type: ["3v3"],
    displayName: "Angermünde",
    autoMatch: true,
    maxPlayers: 6,
  },
  "6p_ettelbruck_station": {
    type: ["3v3"],
    displayName: "Ettelbruck Station",
    autoMatch: true,
    maxPlayers: 6,
  },
  "6p_hill_400": {
    type: ["3v3"],
    displayName: "Hill 400",
    autoMatch: true,
    maxPlayers: 6,
  },
  "4_6_lemberg_fall": {
    type: ["3v3"],
    displayName: "Lemberg Fall 1944",
    autoMatch: false,
    maxPlayers: 6,
  },
  "6p_montherme": {
    type: ["3v3"],
    displayName: "Montherme",
    autoMatch: false,
    maxPlayers: 6,
  },
  "4p_rzhev_summer_frontline": {
    type: ["3v3"],
    displayName: "Rzhev",
    autoMatch: false,
    maxPlayers: 6,
  },
  "6p_wolfs_lair": {
    type: ["3v3"],
    displayName: "Wolfs Lair",
    autoMatch: false,
    maxPlayers: 6,
  },
  "8p_achelous_river": {
    type: ["3v3"],
    displayName: "Achelous River",
    autoMatch: false,
    maxPlayers: 6,
  },
  "6p_anklet": {
    type: ["3v3"],
    displayName: "Anklet & Archery",
    autoMatch: false,
    maxPlayers: 6,
  },
  "6p_general_mud": {
    type: ["3v3"],
    displayName: "General Mud",
    autoMatch: false,
    maxPlayers: 6,
  },
  "4p_coh2_okariver_frontline_primary": {
    type: ["3v3"],
    displayName: "Oka River Winter",
    autoMatch: false,
    maxPlayers: 6,
  },
  "6p_pavlovs_house": {
    type: ["3v3"],
    displayName: "Pavlov's House",
    autoMatch: false,
    maxPlayers: 6,
  },
  // 2v2 Maps
  "4p_vaux_farmlands": {
    type: ["2v2"],
    displayName: "Vaux Farmlands",
    autoMatch: true,
    maxPlayers: 4,
  },
  "4p_fields_of_winnekendonk": {
    type: ["2v2"],
    displayName: "Fields of Winnekendonk",
    autoMatch: true,
    maxPlayers: 4,
  },
  "4p_minsk_pocket_frontline": {
    type: ["2v2"],
    displayName: "Minsk Pocket",
    autoMatch: true,
    maxPlayers: 4,
  },
  "4p_moscow_outskirts_fall_frontline": {
    type: ["2v2"],
    displayName: "Moscow Outskirts",
    autoMatch: true,
    maxPlayers: 4,
  },
  "4p_dreux_scout": {
    type: ["2v2"],
    displayName: "Dreux Scout",
    autoMatch: true,
    maxPlayers: 4,
  },
  "4p_elst_outskirts": {
    type: ["2v2"],
    displayName: "Elst Outskirts",
    autoMatch: true,
    maxPlayers: 4,
  },
  "4p_road_to_kharkov": {
    type: ["2v2"],
    displayName: "Road to Kharkov",
    autoMatch: true,
    maxPlayers: 4,
  },
  wolfheze: {
    type: ["2v2"],
    displayName: "Wolfheze",
    autoMatch: true,
    maxPlayers: 4,
  },
  "4p_rails_and_metal": {
    type: ["2v2"],
    displayName: "Rails and Metal",
    autoMatch: true,
    maxPlayers: 4,
  },
  "4p_belgorod": {
    type: ["2v2"],
    displayName: "Belgorod",
    autoMatch: true,
    maxPlayers: 4,
  },
  "4p_crossing_in_the_woods": {
    type: ["2v2"],
    displayName: "Crossing in the Woods",
    autoMatch: true,
    maxPlayers: 4,
  },
  aod: {
    type: ["2v2"],
    displayName: "Arnhem Outskirts",
    autoMatch: true,
    maxPlayers: 4,
  },
  "4p_einhoven_country": {
    type: ["2v2"],
    displayName: "Eindhoven Country",
    autoMatch: true,
    maxPlayers: 4,
  },
  highwaybaku: {
    type: ["2v2"],
    displayName: "Highway to Baku",
    autoMatch: true,
    maxPlayers: 4,
  },
  "4p_bystraya_voda": {
    type: ["2v2"],
    displayName: "Bystraya Voda",
    autoMatch: false,
    maxPlayers: 4,
  },
  "2p_don_river": {
    type: ["2v2"],
    displayName: "Don River",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_ecliptic_fields": {
    type: ["2v2"],
    displayName: "Ecliptic Fields",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_gelsenkirchen_refinery": {
    type: ["2v2"],
    displayName: "Gelsenkirchen Refinery",
    autoMatch: false,
    maxPlayers: 4,
  },
  "2p_karelia": {
    type: ["2v2"],
    displayName: "Karelia Summer",
    autoMatch: false,
    maxPlayers: 4,
  },
  "2p_cheneux": {
    type: ["2v2"],
    displayName: "Lierneux",
    autoMatch: false,
    maxPlayers: 4,
  },
  overgrowth: {
    type: ["2v2"],
    displayName: "Overgrowth",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_prypiat_frontline_primary": {
    type: ["2v2"],
    displayName: "Pripyat",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_prypiat_winter_frontline_primary": {
    type: ["2v2"],
    displayName: "Pripyat Winter",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_semois": {
    type: ["2v2"],
    displayName: "Semoskiy",
    autoMatch: false,
    maxPlayers: 4,
  },
  "2_4_terek_lines": {
    type: ["2v2"],
    displayName: "Terek Lines",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_across_the_rhine": {
    type: ["2v2"],
    displayName: "Across the Rhine",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_alliance of defiance": {
    type: ["2v2"],
    displayName: "Alliance of Defiance",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_dusseldorf": {
    type: ["2v2"],
    displayName: "Düsseldorf",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_ettelbruck_station": {
    type: ["2v2"],
    displayName: "Ettelbruck Station",
    autoMatch: false,
    maxPlayers: 4,
  },
  hamlet: {
    type: ["2v2"],
    displayName: "Hamlet",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_heidelberg_crossings": {
    type: ["2v2"],
    displayName: "Heidelberg Crossings",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_lisores": {
    type: ["2v2"],
    displayName: "Lisores River",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_minsk_pocket_frontline_primary": {
    type: ["2v2"],
    displayName: "Minsk Pocket",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_moscow_outskirts_frontline_primary": {
    type: ["2v2"],
    displayName: "Moscow Outskirts Winter",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_noville_encirclement": {
    type: ["2v2"],
    displayName: "Noville Encirclement",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_poltawa": {
    type: ["2v2"],
    displayName: "Poltawa",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_pripyat_sector": {
    type: ["2v2"],
    displayName: "Pripyat Sector",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_rzhev_frontline_primary": {
    type: ["2v2"],
    displayName: "Rzhev Winter",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_schilberg_outskirts": {
    type: ["2v2"],
    displayName: "Schilberg Outskirts",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_semois_winter": {
    type: ["2v2"],
    displayName: "Semoskiy Winter",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_stadtschutt": {
    type: ["2v2"],
    displayName: "Stadtschutt",
    autoMatch: false,
    maxPlayers: 4,
  },
  // 1v1 Maps
  ploiesti: {
    type: ["1v1"],
    displayName: "Ploiesti Outskirts",
    autoMatch: true,
    maxPlayers: 2,
  },
  "2p_crossing_in_the_woods": {
    type: ["1v1"],
    displayName: "Crossing in the Woods",
    autoMatch: true,
    maxPlayers: 2,
  },
  bocage: {
    type: ["1v1"],
    displayName: "Bocage",
    autoMatch: true,
    maxPlayers: 2,
  },
  langres: {
    type: ["1v1"],
    displayName: "Langreskaya",
    autoMatch: true,
    maxPlayers: 2,
  },
  nexus: {
    type: ["1v1"],
    displayName: "Nexus",
    autoMatch: true,
    maxPlayers: 2,
  },
  vilshanka: {
    type: ["1v1"],
    displayName: "Vilshanka",
    autoMatch: true,
    maxPlayers: 2,
  },
  "2p_bayeux": {
    type: ["1v1"],
    displayName: "Bayeux",
    autoMatch: true,
    maxPlayers: 2,
  },
  "2p_faymonville_approach": {
    type: ["1v1"],
    displayName: "Faymonville Approach",
    autoMatch: true,
    maxPlayers: 2,
  },
  "2p_kholodnaya_ferma_spring_frontline": {
    type: ["1v1"],
    displayName: "Kholodny Ferma",
    autoMatch: true,
    maxPlayers: 2,
  },
  amilly_fields: {
    type: ["1v1"],
    displayName: "Amilly Fields",
    autoMatch: true,
    maxPlayers: 2,
  },
  crossroadswx: {
    type: ["1v1"],
    displayName: "Crossroads Winter",
    autoMatch: true,
    maxPlayers: 2,
  },
  mill_road: {
    type: ["1v1"],
    displayName: "Mill Road",
    autoMatch: true,
    maxPlayers: 2,
  },
  crossroads: {
    type: ["1v1"],
    displayName: "Crossroads",
    autoMatch: true,
    maxPlayers: 2,
  },
  "2p_ladoga_karelia": {
    type: ["1v1"],
    displayName: "Ladoga Karelia",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_nexus": {
    type: ["1v1"],
    displayName: "Nexus",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_rechnaya_pereprava": {
    type: ["1v1"],
    displayName: "Rechnaya Pereprava",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_southern_alblasserwaard": {
    type: ["1v1"],
    displayName: "Southern Alblasserwaard",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_angoville_farms": {
    type: ["1v1"],
    displayName: "Angoville",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_arnhem_checkpoint": {
    type: ["1v1"],
    displayName: "Arnhem Checkpoint",
    autoMatch: false,
    maxPlayers: 2,
  },
  "4p_bialystok_market": {
    type: ["1v1"],
    displayName: "Bialystok Market",
    autoMatch: false,
    maxPlayers: 4,
  },
  "2p_bombarded_refinery": {
    type: ["1v1"],
    displayName: "Bombarded Refinery",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_bryansk_forest": {
    type: ["1v1"],
    displayName: "Bryansk Forest",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_caen": {
    type: ["1v1"],
    displayName: "Caen",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_halbe": {
    type: ["1v1"],
    displayName: "Halbe",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_kholodnaya_ferma_spring_frontline_primary": {
    type: ["1v1"],
    displayName: "Kholodny Ferma",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_kholodnaya_ferma_battlefield_primary": {
    type: ["1v1"],
    displayName: "Kholodny Ferma Winter",
    autoMatch: false,
    maxPlayers: 2,
  },
  "4p_kholodnaya_ferma_battlefield_tow": {
    type: ["1v1"],
    displayName: "Kholodny Ferma Winter",
    autoMatch: false,
    maxPlayers: 4,
  },
  "2p_la_gleize_breakout": {
    type: ["1v1"],
    displayName: "La Gleize Breakout",
    autoMatch: false,
    maxPlayers: 2,
  },
  "(2-4)_langres": {
    type: ["1v1"],
    displayName: "Langreskaya",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2-4_langres_winter": {
    type: ["1v1"],
    displayName: "Langreskaya Winter",
    autoMatch: false,
    maxPlayers: 2,
  },
  lost_glider: {
    type: ["1v1"],
    displayName: "Lost Glider",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_market_ruins": {
    type: ["1v1"],
    displayName: "Market Ruins",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_minsk_pocket_frontline": {
    type: ["1v1"],
    displayName: "Minsk Pocket",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_novgorodoutskirts": {
    type: ["1v1"],
    displayName: "Novgorod Outskirts",
    autoMatch: false,
    maxPlayers: 2,
  },
  "4p_ponaryforest": {
    type: ["1v1"],
    displayName: "Ponary Forest",
    autoMatch: false,
    maxPlayers: 4,
  },
  "2p_road_to_kharkov": {
    type: ["1v1"],
    displayName: "Road to Kharkov",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_rustungswerke_essen": {
    type: ["1v1"],
    displayName: "Rüstungswerke Essen",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_semois_winter": {
    type: ["1v1"],
    displayName: "Semoskiy Winter",
    autoMatch: false,
    maxPlayers: 2,
  },
  "(2)_resistence_dlc_1_test": {
    type: ["1v1"],
    displayName: "Stalingrad",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_sturzdorf": {
    type: ["1v1"],
    displayName: "Sturzdorf",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_westwall": {
    type: ["1v1"],
    displayName: "Westwall",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_ploiesti": {
    type: ["1v1"],
    displayName: "Ploiesti Outskirts",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_bocage": {
    type: ["1v1"],
    displayName: "Bocage",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_amilly_fields": {
    type: ["1v1"],
    displayName: "Amilly Fields",
    autoMatch: false,
    maxPlayers: 2,
  },
  "2p_mill_road": {
    type: ["1v1"],
    displayName: "Mill Road",
    autoMatch: false,
    maxPlayers: 2,
  },
  "4p_wolfheze": {
    type: ["1v1"],
    displayName: "Wolfheze",
    autoMatch: false,
    maxPlayers: 4,
  },
  "4p_highwaybaku": {
    type: ["1v1"],
    displayName: "Highway to Baku",
    autoMatch: false,
    maxPlayers: 4,
  },
  crossroads_winter: {
    type: ["1v1"],
    displayName: "Crossroads Winter",
    autoMatch: false,
    maxPlayers: 2,
  },
}


export { getMapIconPath };
