name: Build and Deploy Web - PRODUCTION
on:
  push:
    tags:
      - v*
    paths-ignore:
      - packages/app/**

env:
  COOLIFY_BASE_URL: https://coolify.coh3stats.com
  COOLIFY_UUID_PROD: jp124nyfu6drmvbxxbi6pcno

jobs:
  build-deploy-web:
    name: Deploy Web Prod
    environment:
      name: prod
      url: https://coh2stats.com/
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Coolify
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_DEPLOY_TOKEN }}" \
            -H "Content-Type: application/json" \
            "${{ env.COOLIFY_BASE_URL }}/api/v1/deploy?uuid=${{ env.COOLIFY_UUID_PROD }}&force=false"
